export const url = 'https://norma.nomoreparties.space/api'
export const LOG_IN = 'login'
export const REGISTRATION = 'registration'
export const FORGOT_PASSWORD = 'forgotPassword'
export const RESET_PASSWORD= 'ressetpassword'
export const PROFILE = 'profile'
export const TOKEN = 'token'
export const REFRESH_TOKEN = 'refreshtoken'
export const PASSWORD = 'password'
export const ISLOGIN = 'islogin'
export const USER = 'user'
export const ISPENDING = 'Ваш заказ готовится'
export const INGREDIENTMODAL = 'ingredient_modal'
export const ORDERMODAL = 'order_modal'
export const IDFORMODAL = 'id_for_modal'
export const ORDERID = 'order_id'
export const itemTypes = {
    INGREDIENT: 'ingredient',
    MAIN: 'main'
}